
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 15 20:41:28 CEST 2025
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 2;
  public static final int CONST = 39;
  public static final int POR = 5;
  public static final int PUNTOYCOMA = 27;
  public static final int PCIERRE = 20;
  public static final int CASE = 47;
  public static final int INT = 29;
  public static final int FOR = 43;
  public static final int NOT = 15;
  public static final int MENORIGUAL = 11;
  public static final int AND = 13;
  public static final int IGUAL = 7;
  public static final int TYPE = 32;
  public static final int OR = 14;
  public static final int BOOL = 30;
  public static final int CLASS = 40;
  public static final int CONTPUNT = 18;
  public static final int DIV = 28;
  public static final int CC = 22;
  public static final int IF = 50;
  public static final int MAIN = 26;
  public static final int THIS = 37;
  public static final int CA = 21;
  public static final int MAYORIGUAL = 12;
  public static final int DIST = 8;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 24;
  public static final int RETURN = 45;
  public static final int LLAVEAPERTURA = 23;
  public static final int TRUE = 33;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int MENOS = 4;
  public static final int NULL = 38;
  public static final int MENOR = 9;
  public static final int MOD = 6;
  public static final int CIN = 51;
  public static final int DIRECCION = 17;
  public static final int BREAK = 42;
  public static final int VOID = 41;
  public static final int SWITCH = 48;
  public static final int ASIGNACION = 16;
  public static final int REAL = 56;
  public static final int MAYOR = 10;
  public static final int ENT = 55;
  public static final int PAP = 19;
  public static final int FLECHA = 36;
  public static final int ELSE = 49;
  public static final int COUT = 52;
  public static final int IDEN = 54;
  public static final int WHILE = 44;
  public static final int ACCESO = 53;
  public static final int DEFAULT = 46;
  public static final int FALSE = 34;
  public static final int STRUCT = 35;
  public static final int MAS = 3;
}

