package ast;

public enum KindE {
	NULL, IDENTIFIER, NUM, BOOLEAN, FLOAT, NOT, MENOR, MAYOR, MENORIGUAL, MAYORIGUAL, IGUAL, DIST, AND, OR, SUMA, RESTA, MULTIPLICACION, MODULO, DIVISION, ACCESO_ARRAY, ACCESO_DIRECCION, FLECHA, STRUCT, THIS, ACCESO_PUNT, NEW, INSTRUCCION, INCR, DECR, NEGATIVO
}
